FROM node:10-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
# create a dir inside image which will hold our app
WORKDIR /home/node/app
# copy package and package-lock to image
COPY package*.json ./
# switch to node user so that he owns all application code and node_modules
USER node
RUN npm ci
# bundle app source inside image
COPY --chown=node:node . .
# finally, run tests
CMD ["npm", "run", "test"]
