version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 14.15.3
      - node/test:
          version: 12.20.0
      - node/test:
          version: 10.23.0